### PR TITLE
added tanh distortion

### PR DESCRIPTION
**Pull request by drart**

### CODE REVIEW

**Comment by colinbdclark** [comment]
Hi @drart, this looks awesome! Thanks for the contribution. Any chance you'd be willing to also create a simple demo and documentation page for this unit generator? I'm happy to merge the pull regardless, and I certainly have created tons of ugens that don't have documentation, but it might be great to have some for the start for this new one. Let me know if you have the cycles for this. Bonus points for a unit test!

**Comment by drart** [comment]
No bonus points yet, but I have added documentation for all ugens. I included a demo for the tanh distortion, but I would be happy to work up some demos for the other undemoed distortions.

**Comment by colinbdclark** [comment]
@drart This pull request is awesome. I have made some modifications to it in #223, which you can take a look at for reference. Just for housekeeping, I'm closing this PR in favour of #223. Thanks so much for these improvements, they're great!

**Comment by colinbdclark** [comment]
It's in! Merged at e64720c8d3dd1254f1addec3e86f8af38e8dcba5. Thank you again so much for this, @drart. Your distortion demos sound awesome!

**Pull request closed without merging**
